export interface Tool {
  slug: string
  title: string
  shortTitle: string
  description: string
  longDescription: string
  icon: string
  color: string
  iconColor: string
  accept: string
  maxFiles: number
  maxSize: number
  action: string
  category: 'organize' | 'convert' | 'optimize' | 'create'
  keywords: string[]
}

export const tools: Tool[] = [
  {
    slug: 'merge-pdf',
    title: 'Merge PDF',
    shortTitle: 'Merge',
    description: 'Combine multiple PDF files into one document in seconds.',
    longDescription: 'Merge multiple PDF files into a single document. Drag and arrange pages in the order you want, then download your combined PDF instantly.',
    icon: 'merge',
    color: 'bg-violet-50',
    iconColor: '#7c3aed',
    accept: 'application/pdf',
    maxFiles: 20,
    maxSize: 100 * 1024 * 1024,
    action: 'merge',
    category: 'organize',
    keywords: ['merge pdf', 'combine pdf', 'join pdf files', 'pdf merger online'],
  },
  {
    slug: 'split-pdf',
    title: 'Split PDF',
    shortTitle: 'Split',
    description: 'Separate PDF pages into individual files or custom ranges.',
    longDescription: 'Split your PDF into separate pages, or extract a specific range of pages. Choose exactly which pages to extract with our intuitive page picker.',
    icon: 'split',
    color: 'bg-blue-50',
    iconColor: '#2563eb',
    accept: 'application/pdf',
    maxFiles: 1,
    maxSize: 100 * 1024 * 1024,
    action: 'split',
    category: 'organize',
    keywords: ['split pdf', 'divide pdf', 'extract pdf pages', 'pdf splitter online'],
  },
  {
    slug: 'compress-pdf',
    title: 'Compress PDF',
    shortTitle: 'Compress',
    description: 'Reduce PDF file size without losing visible quality.',
    longDescription: 'Shrink your PDF files to a fraction of their original size. Our smart compression algorithm reduces file size while preserving readability.',
    icon: 'compress',
    color: 'bg-emerald-50',
    iconColor: '#059669',
    accept: 'application/pdf',
    maxFiles: 1,
    maxSize: 100 * 1024 * 1024,
    action: 'compress',
    category: 'optimize',
    keywords: ['compress pdf', 'reduce pdf size', 'shrink pdf', 'pdf compressor online'],
  },
  {
    slug: 'pdf-to-word',
    title: 'PDF to Word',
    shortTitle: 'PDF → Word',
    description: 'Convert PDF files to editable Word documents (.docx).',
    longDescription: 'Convert your PDF files into fully editable Word documents. Preserve fonts, layouts, and formatting for seamless editing in Microsoft Word.',
    icon: 'pdf-word',
    color: 'bg-sky-50',
    iconColor: '#0284c7',
    accept: 'application/pdf',
    maxFiles: 1,
    maxSize: 50 * 1024 * 1024,
    action: 'pdf-to-word',
    category: 'convert',
    keywords: ['pdf to word', 'convert pdf to docx', 'pdf to word converter online'],
  },
  {
    slug: 'word-to-pdf',
    title: 'Word to PDF',
    shortTitle: 'Word → PDF',
    description: 'Convert Word documents to PDF with perfect formatting.',
    longDescription: 'Turn your Word documents (.doc, .docx) into PDFs that look exactly as intended. Preserve all formatting, images, and layout.',
    icon: 'word-pdf',
    color: 'bg-indigo-50',
    iconColor: '#4f46e5',
    accept: '.doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    maxFiles: 1,
    maxSize: 50 * 1024 * 1024,
    action: 'word-to-pdf',
    category: 'convert',
    keywords: ['word to pdf', 'convert docx to pdf', 'word document to pdf online'],
  },
  {
    slug: 'image-to-pdf',
    title: 'Image to PDF',
    shortTitle: 'Image → PDF',
    description: 'Convert JPG, PNG, and other images to PDF documents.',
    longDescription: 'Convert images (JPG, PNG, WebP, TIFF) into PDF files. Arrange multiple images into a single PDF document with custom page sizing.',
    icon: 'image-pdf',
    color: 'bg-orange-50',
    iconColor: '#ea580c',
    accept: 'image/jpeg,image/png,image/webp,image/tiff',
    maxFiles: 20,
    maxSize: 50 * 1024 * 1024,
    action: 'image-to-pdf',
    category: 'convert',
    keywords: ['image to pdf', 'jpg to pdf', 'png to pdf', 'convert image to pdf online'],
  },
  {
    slug: 'rotate-pdf',
    title: 'Rotate PDF',
    shortTitle: 'Rotate',
    description: 'Rotate PDF pages to the correct orientation in one click.',
    longDescription: 'Rotate all or specific pages in your PDF. Fix upside-down scans or adjust landscape/portrait orientation with precision.',
    icon: 'rotate',
    color: 'bg-pink-50',
    iconColor: '#db2777',
    accept: 'application/pdf',
    maxFiles: 1,
    maxSize: 100 * 1024 * 1024,
    action: 'rotate',
    category: 'organize',
    keywords: ['rotate pdf', 'turn pdf pages', 'fix pdf orientation online'],
  },
  {
    slug: 'pdf-to-jpg',
    title: 'PDF to JPG',
    shortTitle: 'PDF → JPG',
    description: 'Extract pages from PDFs as high-quality JPG images.',
    longDescription: 'Convert every page of your PDF to high-quality JPG images. Choose resolution (72–300 DPI) and download all pages individually.',
    icon: 'pdf-jpg',
    color: 'bg-amber-50',
    iconColor: '#d97706',
    accept: 'application/pdf',
    maxFiles: 1,
    maxSize: 100 * 1024 * 1024,
    action: 'pdf-to-jpg',
    category: 'convert',
    keywords: ['pdf to jpg', 'convert pdf to image', 'pdf to jpeg online'],
  },
  {
    slug: 'protect-pdf',
    title: 'Protect PDF',
    shortTitle: 'Protect',
    description: 'Password-protect your PDF to prevent unauthorized access.',
    longDescription: 'Add a password to your PDF file to keep it secure. Anyone who opens the file will need to enter the password you set.',
    icon: 'protect',
    color: 'bg-red-50',
    iconColor: '#dc2626',
    accept: 'application/pdf',
    maxFiles: 1,
    maxSize: 100 * 1024 * 1024,
    action: 'protect',
    category: 'optimize',
    keywords: ['protect pdf', 'password pdf', 'encrypt pdf', 'lock pdf online'],
  },
  {
    slug: 'page-numbers',
    title: 'Add Page Numbers',
    shortTitle: 'Page Numbers',
    description: 'Stamp page numbers onto every page of your PDF.',
    longDescription: 'Add page numbers to your PDF with full control over position (top/bottom, left/center/right), starting number, and font size.',
    icon: 'page-numbers',
    color: 'bg-teal-50',
    iconColor: '#0d9488',
    accept: 'application/pdf',
    maxFiles: 1,
    maxSize: 100 * 1024 * 1024,
    action: 'page-numbers',
    category: 'organize',
    keywords: ['add page numbers to pdf', 'number pdf pages', 'pdf page numbering online'],
  },

  {
  slug: 'watermark-pdf',
  title: 'Watermark PDF',
  shortTitle: 'Watermark',
  description: 'Add text watermark to your PDF.',
  longDescription: 'Add a custom text watermark to your PDF pages to protect your content.',
  icon: 'watermark',
  color: 'bg-purple-50',
  iconColor: '#7c3aed',
  accept: 'application/pdf',
  maxFiles: 1,
  maxSize: 100 * 1024 * 1024,
  action: 'watermark',
  category: 'optimize',
  keywords: ['watermark pdf', 'add watermark', 'protect pdf'],
},

{
  slug: 'extract-pages',
  title: 'Extract Pages',
  shortTitle: 'Extract',
  description: 'Extract specific pages from a PDF.',
  longDescription: 'Select and extract specific pages from your PDF into a new file.',
  icon: 'extract',
  color: 'bg-green-50',
  iconColor: '#16a34a',
  accept: 'application/pdf',
  maxFiles: 1,
  maxSize: 100 * 1024 * 1024,
  action: 'extract-pages',
  category: 'organize',
  keywords: ['extract pages pdf', 'split specific pages'],
},

{
  slug: 'image-watermark',
  title: 'Add Image Watermark',
  shortTitle: 'Image Watermark',
  description: 'Add logo or image watermark to PDF.',
  longDescription: 'Upload an image and add it as a watermark on all pages of your PDF.',
  icon: 'image',
  color: 'bg-indigo-50',
  iconColor: '#4f46e5',
  accept: 'application/pdf,image/png,image/jpeg',
  maxFiles: 2,
  maxSize: 100 * 1024 * 1024,
  action: 'image-watermark',
  category: 'optimize',
  keywords: ['image watermark pdf', 'logo watermark'],
},


{
  slug: 'pdf-to-ppt',
  title: 'PDF to PowerPoint',
  shortTitle: 'PDF to PPT',
  description: 'Convert PDF to PowerPoint slides.',
  longDescription: 'Convert each PDF page into a PowerPoint slide.',
  icon: 'ppt',
  color: 'bg-orange-50',
  iconColor: '#ea580c',
  accept: 'application/pdf',
  maxFiles: 1,
  maxSize: 100 * 1024 * 1024,
  action: 'to-ppt',
  category: 'convert',
  keywords: ['pdf to ppt', 'convert pdf to powerpoint'],
},

{
  slug: 'presentation-maker',
  title: 'Presentation Maker',
  shortTitle: 'Presentations',
  description: 'Create beautiful PowerPoint presentations online.',
  longDescription: 'Build slide presentations with custom themes, layouts, and images. Download as PPTX.',
  icon: 'ppt',
  color: 'bg-indigo-50',
  iconColor: '#6366f1',
  accept: '',
  maxFiles: 0,
  maxSize: 0,
  action: '',
  category: 'create',
  keywords: ['presentation maker', 'create pptx', 'make powerpoint online'],
},

{
  slug: 'edit-pdf',
  title: 'Edit PDF',
  shortTitle: 'Edit PDF',
  description: 'Add text, signatures and shapes to your PDF.',
  longDescription: 'Edit PDF files by adding text, drawing signatures, and placing shapes anywhere on the page.',
  icon: 'edit',
  color: 'bg-violet-50',
  iconColor: '#7c3aed',
  accept: 'application/pdf',
  maxFiles: 1,
  maxSize: 50 * 1024 * 1024,
  action: '',
  category: 'organize',
  keywords: ['edit pdf', 'add text to pdf', 'sign pdf', 'annotate pdf online'],
},
{
  slug: 'pdf-to-excel',
  title: 'PDF to Excel',
  shortTitle: 'PDF → Excel',
  description: 'Convert PDF tables and data to Excel spreadsheets.',
  longDescription: 'Extract tables and data from PDF files and convert them into editable Excel spreadsheets.',
  icon: 'excel',
  color: 'bg-green-50',
  iconColor: '#16a34a',
  accept: 'application/pdf',
  maxFiles: 1,
  maxSize: 50 * 1024 * 1024,
  action: 'pdf-to-excel',
  category: 'convert',
  keywords: ['pdf to excel', 'pdf to xlsx', 'convert pdf to spreadsheet online'],
},

{
  slug: 'excel-to-pdf',
  title: 'Excel to PDF',
  shortTitle: 'Excel → PDF',
  description: 'Convert Excel spreadsheets to PDF documents.',
  longDescription: 'Convert your .xls and .xlsx files into PDF documents. Preserves all sheets, tables, and formatting.',
  icon: 'excel',
  color: 'bg-green-50',
  iconColor: '#16a34a',
  accept: '.xls,.xlsx,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  maxFiles: 1,
  maxSize: 50 * 1024 * 1024,
  action: 'excel-to-pdf',
  category: 'convert',
  keywords: ['excel to pdf', 'xlsx to pdf', 'convert spreadsheet to pdf online'],
},
{
  slug: 'ppt-to-pdf',
  title: 'PowerPoint to PDF',
  shortTitle: 'PPT → PDF',
  description: 'Convert PowerPoint presentations to PDF documents.',
  longDescription: 'Convert your .ppt and .pptx files into PDF documents. Preserves all slides, layouts, and formatting.',
  icon: 'ppt',
  color: 'bg-orange-50',
  iconColor: '#ea580c',
  accept: '.ppt,.pptx,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation',
  maxFiles: 1,
  maxSize: 100 * 1024 * 1024,
  action: 'ppt-to-pdf',
  category: 'convert',
  keywords: ['ppt to pdf', 'powerpoint to pdf', 'convert pptx to pdf online'],
},

{
  slug: 'remove-pages',
  title: 'Remove Pages',
  shortTitle: 'Remove Pages',
  description: 'Delete specific pages from your PDF.',
  longDescription: 'Remove unwanted pages from your PDF file by selecting page numbers.',
  icon: 'remove',
  color: 'bg-red-50',
  iconColor: '#dc2626',
  accept: 'application/pdf',
  maxFiles: 1,
  maxSize: 100 * 1024 * 1024,
  action: 'remove-pages',
  category: 'organize',
  keywords: ['remove pages pdf', 'delete pdf pages'],
}


]

export const categories = {
  organize: { label: 'Organize', description: 'Merge, split, and rearrange PDF pages' },
  convert:  { label: 'Convert',  description: 'Convert PDFs to and from other formats' },
  optimize: { label: 'Optimize', description: 'Compress and clean up PDF files' },
  // ✅ ADD THIS:
  create:   { label: 'Create',   description: 'Build documents and presentations from scratch' },
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find(t => t.slug === slug)
}

export function getToolsByCategory(category: Tool['category']): Tool[] {
  return tools.filter(t => t.category === category)
}

export function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 Bytes'
  const k = 1024
  const sizes = ['Bytes', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}